
# cmakePack.cmake


# Specify various generic-package distribuation properties
# set(CPACK_PACKAGE_NAME ${PROJECT_NAME}) # same as default
set(CPACK_PACKAGE_VENDOR "Transpixel.org")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PROJECT_VERSION_TWEAK})


include("${CMAKE_SOURCE_DIR}/cmake/cmakePackDEB.cmake")

